### PR TITLE
Update to Substrate & Frontier v3.0

### PR DESCRIPTION
**Pull request by stiiifff**

### CODE REVIEW

**Comment by kotlarmilos** [comment]
Thank you for the PR! 

I am still not able to compile the project due to `fp-rpc, pallet-ethereum, and pallet-evm-precompile-simple` dependencies from https://github.com/paritytech/frontier repository. 

Screenshot 2021-04-08 at 13 25 55

Also, which WASM build toolchain should we use?

**Comment by sbp-parity** [comment]
Can you retry with the latest stable (rust v1.51) ? No need to use (anymore) the specific nightly version.

**Comment by kotlarmilos** [comment]
Still the same. I can't find the target version (0.1.0) on the repository, there is only 1.0.0. Should we take that one perhaps?
https://github.com/paritytech/frontier/blob/f00852a00505e81d2b10d8ca2f12e54acd185871/primitives/rpc/Cargo.toml#L3

Screenshot 2021-04-09 at 09 41 01

**Comment by stiiifff** [comment]
@kotlarmilos The latest frontier -related crates have been published to crates.io, so you can now target released versions.
Can you give it another go ?

**Comment by NZT48** [comment]
@stiiifff Starfleet-Node right now works as standalone, but when I try to run local private network, blocks are not finalized, and have this message:
` add_set_reserved_peer with unknown protocol: /paritytech/grandpa/1`
I couldn't find any solution for this, and I tried to start network with my keys, and with predefined Alice and Bob keys, in each case there was the same problem. Thank you for help

**Comment by stiiifff** [comment]
@NZT48 Fixed by #7

**Pull request merged**
